server:
  port: 8501


spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gdfwzhxt?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 12345


mybatis:
  mapper-locations: classpath:/mapper/*/*.xml
  config-location: classpath:/mybatis-config.xml


gdfw:
  auth:
    noAuthUrls:
      - /electricity/system/index/login
      - /electricity/system/index/generateValidateCode
      - /electricity/system/index/companyIsExists